routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/home', 'ProductController@index')->name('home');
    
    Route::resource('product', 'ProductController');
    Route::get('/product/{product}/clone', [
        'as'            => 'product.clone', 
        'uses'          => 'ProductController@clone',
    ])->where(['product' => '[0-9]+']);

    Route::resource('item', 'ItemController');
    Route::get('/item/{item}/clone', [
        'as'            => 'item.clone', 
        'uses'          => 'ItemController@clone',
    ])->where(['item' => '[0-9]+']);
    
    Route::resource('fitting', 'FittingController');
    Route::resource('material', 'MaterialController');
    
    Route::get('/pdf/manufacturing', [
        'as'            => 'pdf.manufacturing', 
        'uses'          => 'PdfController@manufacturing',
    ]);
    Route::get('/pdf/price', [
        'as'            => 'pdf.price', 
        'uses'          => 'PdfController@price',
    ]);
});

Auth::routes(['register' => false]);
//Auth::routes();

resources/views/fitting-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-body">
        
        <div class="page-header text-success">
          <h4>Редактирование фурнитуры</h4>      
        </div>
        <hr>

        {!! Form::model($fitting, [
            'method'    => 'PUT',
            'route'     => ['fitting.update', $fitting->id],
            'class'     => 'form-horizontal',
        ]) !!}

        {{ Form::hidden('product_id', $fitting->product_id) }}                    

        <div class="form-group">
            <label>Наименование фурнитуры</label>
            {!! Form::text('name', null, array('class' => 'form-control', 'required')) !!}
        </div>

        <div class="form-group">
            <label>Материал фурнитуры</label>
            {!! Form::text('material', null, array('class' => 'form-control', 'required')) !!}
        </div>

        <div class="form-group">
            <label>Количество (шт.)</label>
            {!! Form::text('count', null, array('class' => 'form-control', 'required')) !!}
        </div>

        <div class="form-group">
            <label>Стоимость (за 1 шт.)</label>
            {!! Form::text('price', null, array('class' => 'form-control', 'required')) !!}
        </div>

        <div class="modal-footer">
            <a href="{{ URL::previous() }}" class="btn btn-secondary">Назад</a>
            {!! Form::submit('Сохранить изменения', array('class' => 'btn btn-primary')) !!}       
        </div>

        {!! Form::close() !!} 

    </div>

@endsection                    

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/material-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-body">
        
        <div class="page-header text-success">
          <h4>Редактирование материала</h4>      
        </div>
        <hr>

        {!! Form::model($material, [
            'method'    => 'PUT',
            'route'     => ['material.update', $material->id],
            'class'     => 'form-horizontal',
        ]) !!}

        <div class="form-group">
          <label>Наименование материала</label>
          {!! Form::text('name', null, array('class' => 'form-control', 'id' => 'material_name', 'required')) !!}
        </div>
        <div class="form-group">
          <label>Стоимость 1 кв.м.</label>
          {!! Form::text('price_material', null, array('class' => 'form-control', 'id' => 'material_price', 'required')) !!}
        </div>
        <div class="form-group">
          <label>Стоимость реза за 1 м.</label>
          {!! Form::text('price_cut', null, array('class' => 'form-control', 'id' => 'material_cut', 'required')) !!}
        </div>

        <div class="modal-footer">
            <a href="{{ URL::previous() }}" class="btn btn-secondary">Назад</a>
            {!! Form::submit('Сохранить изменения', array('class' => 'btn btn-primary')) !!}       
        </div>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/material-index.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-body">
        
        <div class="page-header text-success">
          <h4>Список материалов</h4>      
        </div>
        <hr>
        
        <a href="{{ URL::previous() }}" class="btn btn-secondary">Назад</a>
        <a class="btn btn-success" href="#" data-toggle="modal" data-target="#ModalCreateMaterial">Добавить</a>
        <hr>

        <table id="material-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th scope="col">Наименование материала</th>
                        <th scope="col">Стоимость 1 кв.м.</th>
                        <th scope="col">Стоимость реза за 1 м.</th>
                    </tr>
                </thead>

                <tbody>                    

            @foreach($materials as $material)

            <tr>
                <td>
                    <div class="btn-group">
                      <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ route('material.edit', ['id' => $material->id]) }}"><i data-feather="edit"></i> Редактировать</a>
                        <div class="dropdown-divider"></div>

                        {!! Form::open(['method' => 'DELETE', 'route' => ['material.destroy', $material->id],'onsubmit' => 'return confirm("Вы действительно желаете удалить материал?")']) !!}
                            <a class="dropdown-item" href="#" onclick="$(this).closest('form').submit();"><i data-feather="delete"></i> Удалить</a>
                        {!! Form::close() !!}

                        </a>
                      </div>
                    </div>

                    {{ $material->name }}</td>
                <td>{{ $material->price_material }}</td>
                <td>{{ $material->price_cut }}</td>
            </tr>

            @endforeach

                </tbody>
            </table>

    </div>

<!-- ModalCreateMaterial -->
<div class="modal fade" id="ModalCreateMaterial" tabindex="-1" role="dialog" aria-labelledby="ModalCreateMaterialLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalCreateMaterialLabel">Добавить материал</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {!! Form::open([
            'route'     => 'material.store',
            'class'     => 'form-horizontal',
            'method'    => 'POST'
        ]) !!}

        <div class="form-row">
            <div class="col">
                <label class="control-label">Наименование материала:</label>
                {!! Form::text('name', null, array('class' => 'form-control', 'id' => 'material_name', 'required')) !!}
            </div>
        </div>
        
        <div class="form-row">
            <div class="col">
                <label class="control-label">Стоимость 1 кв.м.:</label>
                {!! Form::number('price_material', null, array('class' => 'form-control', 'id' => 'material_price', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Стоимость реза за 1 м.:</label>
                {!! Form::number('price_cut', null, array('class' => 'form-control', 'id' => 'material_cut', 'required')) !!}
            </div>
        </div>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            {!! Form::submit('Добавить материал', array('class' => 'btn btn-primary')) !!}       
        </div>

        {!! Form::close() !!}          
          
      </div>
    </div>
  </div>
</div>

@endsection

@section('js-footer')

        $('#material-table').DataTable({
            "order": [[ 0, "asc" ]],
            "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "Все"] ],
            "language": {
              "search": "Фильтр:",
              "zeroRecords": "Нет данных для отображения",
              "sLengthMenu": "Отображать _MENU_ записей",
              "info": "Показаны записи _START_ - _END_, всего _TOTAL_ записей",
              "paginate": {
                "previous": "Назад",
                "next": "Дальше"
              }
            }
        });

@endsection

resources/views/product-index.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-body">
        
        <div class="page-header text-success">
          <h4>Список продукции</h4>      
        </div>
        <hr>
        
        <a class="btn btn-success" href="#" data-toggle="modal" data-target="#ModalCreateProduct">Добавить</a>
        <a class="btn btn-primary" href="{{ route('pdf.manufacturing') }}">Стоимость изготовления продукции в PDF</a>
        <a class="btn btn-primary" href="{{ route('pdf.price') }}">Стоимость продукции в PDF</a>
        <hr>
        
        <table id="product-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">PDF</th>
                        <th scope="col">Материал и резка</th>
                        <th scope="col">Фурнитура</th>
                        <th scope="col">Себестоимость</th>
                        <th scope="col">Наценка</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Прибыль</th>
                        <th scope="col">Вес</th>
                    </tr>
                </thead>

                <tbody>                    

            @foreach($products as $product)

                <tr>
                    <td>

                        <div class="btn-group">
                          <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('product.show', ['id' => $product->id]) }}"><i data-feather="file"></i> Состав</a>    
                            <a class="dropdown-item" href="{{ route('product.edit', ['id' => $product->id]) }}"><i data-feather="edit"></i> Редактировать</a>
                            <a class="dropdown-item" href="{{ route('product.clone', ['id' => $product->id]) }}"><i data-feather="copy"></i> Клонировать</a>
                            <div class="dropdown-divider"></div>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['product.destroy', $product->id],'onsubmit' => 'return confirm("Вы действительно желаете удалить продукт?")']) !!}
                                <a class="dropdown-item" href="#" onclick="$(this).closest('form').submit();"><i data-feather="delete"></i> Удалить</a>
                            {!! Form::close() !!}

                            </a>
                          </div>
                        </div>

                        {{ $product->name }}</td>
                    <td>                                
                    @if($product->in_pdf == 'Y')
                        Есть
                    @else
                        Нет
                    @endif
                    </td>
                    <td>
                    @if($product->fix_cost != 0)
                        <b class="text-success">{{ $product->fix_cost }}</b>
                    @else
                        {{ $product->items_sum() }}
                    @endif
                    </td>
                    <td>{{ $product->fittings_sum() }}</td>
                    <td>
                    @if($product->fix_cost != 0)
                        <b class="text-success">{{ $product->fix_cost + $product->fittings_sum() }}</b>
                    @else
                        {{ $product->items_sum() + $product->fittings_sum() }}
                    @endif
                    </td>
                    <td>{{ $product->markup }}%</td>
                    <td>
                    @if($product->fix_cost != 0)
                        <b class="text-success">{{ ($product->fix_cost + $product->fittings_sum()) * ($product->markup / 100 + 1) }}</b>
                    @else
                        {{ ($product->items_sum() + $product->fittings_sum()) * ($product->markup / 100 + 1) }}
                    @endif
                    </td>
                    <td>
                    @if($product->fix_cost != 0)
                        <b class="text-success">{{ (($product->fix_cost + $product->fittings_sum()) * ($product->markup / 100 + 1)) - ($product->fix_cost + $product->fittings_sum()) }}</b>
                    @else
                        {{ (($product->items_sum() + $product->fittings_sum()) * ($product->markup / 100 + 1)) - ($product->items_sum() + $product->fittings_sum()) }}
                    @endif
                        
                        </td>
                    <td>{{ $product->weight }}</td>
                </tr>

            @endforeach

                </tbody>
            </table>

    </div>


<!-- ModalCreateProduct -->
<div class="modal fade" id="ModalCreateProduct" tabindex="-1" role="dialog" aria-labelledby="ModalCreateProductLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalCreateProductLabel">Добавить продукт</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          
        {!! Form::open([
            'route'     => 'product.store',
            'class'     => 'form-horizontal',
            'method'    => 'POST'
        ]) !!}

        <div class="form-row">
            <div class="col">
                <label class="control-label">Наименование:</label>
                {!! Form::text('name', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Наценка (в %):</label>
                {!! Form::number('markup', '50', array('class' => 'form-control', 'required')) !!}
            </div>
        </div>
        
        <div class="form-row">
            <div class="col">
                <label class="control-label">Включить в PDF:</label>
                {!! Form::select('in_pdf', [
                    'N'   => 'Нет',
                    'Y'   => 'Да'
                ], null, array('class' => 'form-control')) !!}
            </div>
            <div class="col">
                <label class="control-label">Сортировка в PDF:</label>
                {!! Form::number('sort', 0, array('class' => 'form-control', 'required')) !!}
            </div>
        </div>

        <div class="form-row">
            <div class="col">
                <label class="control-label">Фикс. стоимость изготовления:</label>
                {!! Form::number('fix_cost', 0, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Фикс. стоимость продукта:</label>
                {!! Form::number('fix_price', 0, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Вес в граммах:</label>
                {!! Form::number('weight', 0, array('class' => 'form-control', 'required')) !!}
            </div>            
        </div>
        
        <p></p>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            {!! Form::submit('Добавить продукт', array('class' => 'btn btn-success')) !!}       
        </div>

        {!! Form::close() !!}          
          
      </div>
    </div>
  </div>
</div>

@endsection

@section('js-footer')

        $('#product-table').DataTable({
            "order": [[ 1, "asc" ]],
            "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "Все"] ],
            "language": {
              "search": "Фильтр:",
              "zeroRecords": "Нет данных для отображения",
              "sLengthMenu": "Отображать _MENU_ записей",
              "info": "Показаны записи _START_ - _END_, всего _TOTAL_ записей",
              "paginate": {
                "previous": "Назад",
                "next": "Дальше"
              }
            }
        });

@endsection

resources/views/product-show.blade.php
@extends('layouts.app')

@section('content')


    <div class="card-body">
        
        <div class="page-header text-success">
          <h4>Состав продукта: <b>{{ $product->name }}</b></h4>      
        </div>
        <hr>
        
        <a href="{{ URL::previous() }}" class="btn btn-secondary">Назад</a>
        <a class="btn btn-info" href="#" data-toggle="modal" data-target="#ModalCreateData">Данные</a>
        <a class="btn btn-success" href="#" data-toggle="modal" data-target="#ModalCreateItem">Добавить акриловый элемент</a>
        <a class="btn btn-success" href="#" data-toggle="modal" data-target="#ModalCreateFitting">Добавить фурнитуру</a>

        <hr>
        <div class="page-header text-secondary">
          <h4>Акриловые элементы</h4>
        </div>
        <hr>
        
            <table id="item-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Материал</th>
                        <th scope="col">Длина/ширина</th>
                        <th scope="col">Стоимость акрила</th>
                        <th scope="col">Рез (метр)</th>
                        <th scope="col">Стоимость реза</th>
                        <th scope="col">Стоимость элемента</th>
                    </tr>
                </thead>

                <tbody>                    

            @foreach($items as $item)

                <tr>
                    <td>
                        
                        <div class="btn-group">
                          <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('item.edit', ['id' => $item->id]) }}"><i data-feather="edit"></i> Редактировать</a>
                            <a class="dropdown-item" href="{{ route('item.clone', ['id' => $item->id]) }}"><i data-feather="copy"></i> Клонировать</a>
                            <div class="dropdown-divider"></div>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['item.destroy', $item->id],'onsubmit' => 'return confirm("Вы действительно желаете удалить элемент?")']) !!}
                                <a class="dropdown-item" href="#" onclick="$(this).closest('form').submit();"><i data-feather="delete"></i> Удалить</a>
                            {!! Form::close() !!}

                            </a>
                          </div>
                        </div>                        
                        
                        {{ $item->name }}</td>
                    <td>{{ $item->material->name }}</td>
                    <td>{{ $item->length }}/{{ $item->width }}</td>
                    <td>{{ $item->price_material }}</td>
                    <td>{{ $item->cut_length/1000 }}</td>
                    <td>{{ $item->price_cut }}</td>
                    <td>{{ $item->price }}</td>
                </tr>

            @endforeach

                </tbody>
            </table>

        <hr>
        <div class="page-header text-secondary">
          <h4>Фурнитура</h4>
        </div>
        <hr>        
        
            <table id="fitting-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Материал</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена за шт.</th>
                        <th scope="col">Стоимость</th>
                    </tr>
                </thead>

                <tbody>                    

            @foreach($fittings as $fitting)

                <tr>
                    <td>
                        
                        <div class="btn-group">
                          <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('fitting.edit', ['id' => $fitting->id]) }}"><i data-feather="edit"></i> Редактировать</a>
                            <div class="dropdown-divider"></div>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['fitting.destroy', $fitting->id],'onsubmit' => 'return confirm("Вы действительно желаете удалить фурнитуру?")']) !!}
                                <a class="dropdown-item" href="#" onclick="$(this).closest('form').submit();"><i data-feather="delete"></i> Удалить</a>
                            {!! Form::close() !!}

                            </a>
                          </div>
                        </div>

                        {{ $fitting->name }}</td>
                    <td>{{ $fitting->material }}</td>
                    <td>{{ $fitting->count }}</td>
                    <td>{{ $fitting->price }} р.</td>
                    <td>{{ $fitting->amount }} р.</td>
                </tr>

            @endforeach

                </tbody>
            </table>
   
    </div>


<!-- ModalCreateItem -->
<div class="modal fade" id="ModalCreateItem" tabindex="-1" role="dialog" aria-labelledby="ModalCreateItemLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalCreateItemLabel">Добавить акриловый элемент</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        {!! Form::open([
            'route'     => 'item.store',
            'class'     => 'form-horizontal',
            'method'    => 'POST'
        ]) !!}

        {{ Form::hidden('product_id', $product->id) }}

        
        <div class="form-row">
            <div class="col">
                <label class="control-label">Наименование:</label>
                {!! Form::text('name', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Материал:</label>
                {!! Form::select('material_id', $material, null, array('class' => 'form-control', 'required')) !!}
            </div>
        </div>

        <div class="form-row">
            <div class="col">
                <label class="control-label">Длина элемента (в мм):</label>
                {!! Form::number('length', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Ширина элемента (в мм):</label>
                {!! Form::number('width', null, array('class' => 'form-control', 'required')) !!}
            </div>
        </div>

        <div class="form-row">
            <div class="col">
                <label class="control-label">Длина реза (в мм):</label>
                {!! Form::number('cut_length', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label"></label>
            </div>
        </div>

        <p></p>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            {!! Form::submit('Добавить элемент', array('class' => 'btn btn-primary')) !!}       
        </div>

        {!! Form::close() !!}          
        
      </div>
    </div>
  </div>
</div>

<!-- ModalCreateFitting -->
<div class="modal fade" id="ModalCreateFitting" tabindex="-1" role="dialog" aria-labelledby="ModalCreateFittingLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalCreateFittingLabel">Добавить фурнитуру</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        
        {!! Form::open([
            'route'     => 'fitting.store',
            'class'     => 'form-horizontal',
            'method'    => 'POST'
        ]) !!}

        {{ Form::hidden('product_id', $product->id) }}                    

        
        <div class="form-row">
            <div class="col">
                <label class="control-label">Наименование:</label>
                {!! Form::text('name', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Материал:</label>
                {!! Form::text('material', null, array('class' => 'form-control', 'required')) !!}
            </div>
        </div>
        
        <div class="form-row">
            <div class="col">
                <label class="control-label">Количество (шт.):</label>
                {!! Form::number('count', null, array('class' => 'form-control', 'required')) !!}
            </div>
            <div class="col">
                <label class="control-label">Стоимость (за 1 шт.):</label>
                {!! Form::number('price', null, array('class' => 'form-control', 'required')) !!}
            </div>
        </div>        

        <p></p>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            {!! Form::submit('Добавить фурнитуру', array('class' => 'btn btn-primary')) !!}       
        </div>

        {!! Form::close() !!}          
        
      </div>
    </div>
  </div>
</div>

<!-- ModalCreateData -->
<div class="modal fade" id="ModalCreateData" tabindex="-1" role="dialog" aria-labelledby="ModalCreateDataLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalCreateDataLabel">Сводные данные продукта: <b>{{ $product->name }}</b></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

          
        <div class="form-row">
            <div class="col">
                <label class="control-label">Материал и резка:</label>
                {{ $product->items_sum() }} р.
            </div>
            <div class="col">
                <label class="control-label">Фурнитура:</label>
                {{ $product->fittings_sum() }} р.
            </div>
            <div class="col">
                <label class="control-label">Себестоимость:</label>
                {{ $product->items_sum() + $product->fittings_sum() }} р.
            </div>            
        </div>
          
        <div class="form-row">
            <div class="col">
                <label class="control-label">Общая длина:</label>
                {{ $product->items_length_sum() }} мм.
            </div>
            <div class="col">
                <label class="control-label">Общая ширина:</label>
                {{ $product->items_width_sum() }} мм.
            </div>
            <div class="col">
                <label class="control-label">Общая цена материала:</label>
                {{ $product->items_price_material_sum() }} р.
            </div>            
        </div>

        <div class="form-row">
            <div class="col">
                <label class="control-label">Общая длина реза:</label>
                {{ $product->items_cut_length_sum()/1000 }} м.
            </div>
            <div class="col">
                <label class="control-label">Общая стоимость реза:</label>
                {{ $product->items_price_cut_sum() }} р.
            </div>
            <div class="col">
                <label class="control-label"></label>
                
            </div>            
        </div>          
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>     
        </div>        
        
      </div>
    </div>
  </div>
</div>

@endsection

@section('js-footer')

        $('#item-table').DataTable({
            "order": [[ 0, "asc" ]],
            "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "Все"] ],
            "language": {
              "search": "Фильтр:",
              "zeroRecords": "Нет данных для отображения",
              "sLengthMenu": "Отображать _MENU_ записей",
              "info": "Показаны записи _START_ - _END_, всего _TOTAL_ записей",
              "paginate": {
                "previous": "Назад",
                "next": "Дальше"
              }
            }
        });

        $('#fitting-table').DataTable({
            "order": [[ 0, "asc" ]],
            "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "Все"] ],
            "language": {
              "search": "Фильтр:",
              "zeroRecords": "Нет данных для отображения",
              "sLengthMenu": "Отображать _MENU_ записей",
              "info": "Показаны записи _START_ - _END_, всего _TOTAL_ записей",
              "paginate": {
                "previous": "Назад",
                "next": "Дальше"
              }
            }
        });        
        
@endsection